version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - download-assets-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - download-assets-network

networks:
  download-assets-network:
    driver: bridge
