version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "5070:80" # Maps port 80 in the container to 5070 on the host
    restart: always

  backend:
    build: ./backend
    ports:
      - "5069:5069"
    restart: always
